### ISSUE TITLE
archive.org sans scripts

### ISSUE THREAD

**Issue by gitut2007** [ddawson/Link-Tools#3]
Hi, if one blocks scripts in archive.org pages, link-tools offers 0 options in both right-click or the URL bar.

**Comment by ddawson** [comment]
Really? Well, the site doesn't seem to work without scripts. But I'm still seeing options in the page action menu. Please tell me the following:

* What version of Link Tools you have.
* What, *exactly*, you are doing to see this problem.
* What, *exactly*, you are seeing. Screenshots may help.

**Comment by gitut2007** [comment]
Maybe the main page doesn't work without scripts, but [depending of the page I guess] saved pages look fine [I stopped arch.org scripts in eg pages that have too many scripts -they eg affect the performance of autoscrolling-].

-What version of Link Tools you have. » Last one.
-What, exactly, you are doing to see this problem. » I right click a link to save an original page link with the archorg part stripped, or I click the  link-tools icon on the URL bar to copy the page URL.
-What, exactly, you are seeing. Screenshots may help. »  for some reason Github is not letting me put screenshots, but it's simple:  link-tools acts same as with not supported pages.

**Comment by gitut2007** [comment]
UPDATE
I just tried 2 archive.org pages with scripts blocked  and  link-tools is working fine...
I don't know what's going on because after I had the problem [yesterday] I updated addons and I didn't see a link-tools update; if I had it occur again I will report, but for now it seems ok...

**Comment by gitut2007** [comment]
Update2
Well, it seems it's not so rare the problem , [but irregular ] .
At the moment: https://www.startpage.com/ , scripts blocked with noscript but allowed in umatrix, link-tools doesn't work.
[Github is still not letting me put screenshots]
clicking URL bar icon: appears a 'no operations available' in a rectangue under the URL bar.
right- clicking a link, hovering or clicking link-tools menu item: nothing appears, no sub-menu items, no warning like in URL bar icon.

**Comment by gitut2007** [comment]
it might be this [i'm not sure/don't remember if it was he case...]: the addon doesn't recognize the page [nor the links in it] if it's in the form  https://web.archive.org/save/https://---.---/ 
[...'save'... instead of say, ...'web'...]

**Comment by ddawson** [comment]
"save"? Well, see, I didn't know about that, so of course it won't be recognized.

I see, that's from its "Save Page Now" feature. I'll add it to the patterns. Is there anything else you can think of along these lines (or just in general) that ought to be added?

BTW, you can see all of the current operations and embedded link patterns by clicking on the toolbar button (over next to the hamburger menu), and clicking the "Edit custom URL operations" button.

**Comment by gitut2007** [comment]
If I think of more I'll post, for now i suggest 
-the other archive services [i don't know the specifics of those, 'resurrect this' addons can give clues]
-options to copy/go from youtube links into: https://www.genyoutube.com/watch?v=0....
[sometimes yt links restricted by age or region, genyt then works]
-maybe proxify links, but this is outside the scope of the addon....

**Comment by ddawson** [comment]
Okay, I added a few archive sites and GenYoutube. Not sure about the last item. Maybe in the future, I can add the ability to have operations that apply to all links. That could work. But I have to write the code for it, so it won't happen right away. (Adding types of links just requires adding things like patterns and substitutions and such, and it's pretty cleanly separated from the rest of the add-on.)
